name: Deploy

on:
  push: {branches: master}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
    - run: npm install
    - run: |
        git config --global user.name 'viuts'
        git config --global user.email 'lukexng@gmail.com'
        npm run publish:github
